version: '3.8'

services:
  db:
    image: postgres:13
    container_name: warehouse
    environment:
      POSTGRES_DB: warehouse_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local